basePath: /
definitions:
  utils.Response:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: API pour le projet PEC2 Backend
  title: API PEC2 Backend
  version: "1.0"
paths:
  /ping:
    get:
      description: Endpoint de test qui répond pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: Ping test
      tags:
      - test
  /users:
    post:
      description: Endpoint for save a user in db
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.Response'
      summary: Users CreateUser
      tags:
      - createUser
swagger: "2.0"
