name: CD

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Déploiement de l'application..."